# Site settings
title: Keshav Karumbunathan MathQuantum Mini-Porject
email: keshavkarumbu0@gmail.com
description: >-
  Website for my MathQuantum Mini_project
github_username: Kuku371
minimal_mistakes_skin: sunrise
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name: "Keshav Karumbunathan"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I am a student at Jesuit High School in Portland, Oregon who is interested in math and computer science."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/keshav-karumbunathan-b92491290"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Kuku371"
    - label: "Gmail"
      icon: "fab fa-google fa-fw"
      url: "https://mail.google.com/mail/u/0/?fs=1&to=keshavkarumbu0@gmail.com&tf=cm"

footer:
  links:
    - label: "Gmail"
      icon: "fab fa-google fa-fw"
      url: "https://mail.google.com/mail/u/0/?fs=1&to=keshavkarumbu0@gmail.com&tf=cm"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/keshav-karumbunathan-b92491290"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Kuku371"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
